### ISSUE TITLE
Errors with handling some smiles strings.

### ISSUE THREAD

**Issue by mzness** [HergenrotherLab/entry-cli#7]
Hi,

I was utilising the entry-cli code to run it with a large set of molecules and encountered the error below about 4 molecules into my set. I noticed it exists on your online platform too.

`Boost.Python.ArgumentError: Python argument types in rdkit.Chem.rdmolops.AddHs(NoneType) did not match C++ signature: AddHs(RDKit::ROMol mol, bool explicitOnly=False, bool addCoords=False, boost::python::api::object onlyOnAtoms=None, bool addResidueInfo=False)`

It is in relation to: `Explicit valence for atom # 17 N, 4, is greater than permitted
Traceback (most recent call last):`

I found previous documentation of this: https://github.com/ReactionMechanismGenerator/RMG-Py/issues/590

It seems like exceptions have to be made for molecules containing 5 or more N's and handled within openbabel rather than RDKIT. I'll be trying to fix this issue just now and will update you if I manage to do so, I thought it was best to bring it your attention.

**Comment by bdrown** [comment]
Are you sure the issue is with multiple nitrogens in a single molecule? I haven't had issues with molecule containing many nitrogens but was able to reproduce the error with uncharged quaternary amines (e.g. `C[N](C)(C)CCC1=CC=CC=C1` instead of `C[N+](C)(C)CCC1=CC=CC=C1`). Does that match the types of compounds you are trying?

**Comment by mzness** [comment]
My apologies, it is in fact to do with uncharged quaternary amines. It makes a lot more sense than what I thought previously and by adding the charge to the SMILES strings it resolved the issue. Thanks.
